### ISSUE TITLE
Unexpectedly got `An unsupported broker version was detected: 3.8.5. The broker must be at least version 3.10.0.` with 7.0.0

### ISSUE THREAD

**Issue by fjmorel** [Particular/NServiceBus.RabbitMQ#1053]
When I saw the 7.0 release, I thought I could update and just set our code to continue to use classic queues by changing
```csharp
transport.UseDirectRoutingTopology(QueueType.Classic);
```

However, when I went to run it, it threw this error:

```
System.Exception: An unsupported broker version was detected: 3.8.5. The broker must be at least version 3.10.0.
   at NServiceBus.Transport.RabbitMQ.ConnectionExtensions.VerifyBrokerRequirements(IConnection connection) in /_/src/NServiceBus.Transport.RabbitMQ/Connection/ConnectionExtensions.cs:line 17
   at NServiceBus.Transport.RabbitMQ.QueueCreator.CreateQueueIfNecessary(QueueBindings queueBindings, String identity) in /_/src/NServiceBus.Transport.RabbitMQ/Administration/QueueCreator.cs:line 21
   at NServiceBus.ReceiveComponent.<>c__DisplayClass3_0.<Initialize>b__0(String identity) in /_/src/NServiceBus.Core/Receiving/ReceiveComponent.cs:line 46
   at NServiceBus.HostingComponent.RunInstallers() in /_/src/NServiceBus.Core/Hosting/HostingComponent.cs:line 59
   at NServiceBus.ExternallyManagedContainerHost.Start(IBuilder externalBuilder) in /_/src/NServiceBus.Core/Hosting/ExternallyManagedContainerHost.cs:line 47
   at NServiceBus.Extensions.Hosting.NServiceBusHostedService.StartAsync(CancellationToken cancellationToken) in /_/src/NServiceBus.Extensions.Hosting/NServiceBusHostedService.cs:line 30
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Main method (cut out for privacy)
```

Is there something that I missed that would let me upgrade this but not RabbitMQ?

Otherwise a notice about change to the minimum supported RabbitMQ version would be nice.

**Comment by fjmorel** [comment]
Oops, I missed that and only looked in this repo. Thanks!
