### ISSUE TITLE
RabbitMQ host stops processing incoming messages

### ISSUE THREAD

**Issue by dsaf** [Particular/NServiceBus.RabbitMQ#125]
Products used: NServiceBus, RabbitMQ, ServiceControl, ServicePulse.

Relevant package versions:
```
NServiceBus 5.2.12
NServiceBus.RabbitMQ 3.0.1
```

Problem: host stops processing messages; a bunch of non-descriptive RabbitMQ-level exceptions are logged.

A host stops processing incoming messages, yet keeps logging this continuously:

```
2016-02-01 13:30:15.0538 DEBUG Polling for timeouts at 01/02/2016 13:30:15. 
2016-02-01 13:30:15.0738 DEBUG Polling next retrieval is at 01/02/2016 13:31:15.
```

There is a lot of RabbitMQ errors in the log - not sure if they are related:

```
2016-02-01 00:05:02.8868 ERROR Failed to receive messages from **SOME_QUEUE** 
One or more errors occurred. System.AggregateException: One or more errors occurred. ---> System.IO.EndOfStreamException: SharedQueue closed
   at RabbitMQ.Util.SharedQueue`1.EnsureIsOpen()
   at RabbitMQ.Util.SharedQueue`1.Dequeue(Int32 millisecondsTimeout, T& result)
   at NServiceBus.Transports.RabbitMQ.RabbitMqDequeueStrategy.ConsumeMessages(Object state) in c:\BuildAgent\work\ef98ad7376e3379a\src\NServiceBus.RabbitMQ\RabbitMqDequeueStrategy.cs:line 234
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.EndOfStreamException: SharedQueue closed
   at RabbitMQ.Util.SharedQueue`1.EnsureIsOpen()
   at RabbitMQ.Util.SharedQueue`1.Dequeue(Int32 millisecondsTimeout, T& result)
   at NServiceBus.Transports.RabbitMQ.RabbitMqDequeueStrategy.ConsumeMessages(Object state) in c:\BuildAgent\work\ef98ad7376e3379a\src\NServiceBus.RabbitMQ\RabbitMqDequeueStrategy.cs:line 234
   at System.Threading.Tasks.Task.Execute()<---
  
SharedQueue closed System.IO.EndOfStreamException: SharedQueue closed
   at RabbitMQ.Util.SharedQueue`1.EnsureIsOpen()
   at RabbitMQ.Util.SharedQueue`1.Dequeue(Int32 millisecondsTimeout, T& result)
   at NServiceBus.Transports.RabbitMQ.RabbitMqDequeueStrategy.ConsumeMessages(Object state) in c:\BuildAgent\work\ef98ad7376e3379a\src\NServiceBus.RabbitMQ\RabbitMqDequeueStrategy.cs:line 234
   at System.Threading.Tasks.Task.Execute() Void EnsureIsOpen()    at RabbitMQ.Util.SharedQueue`1.EnsureIsOpen()
   at RabbitMQ.Util.SharedQueue`1.Dequeue(Int32 millisecondsTimeout, T& result)
   at NServiceBus.Transports.RabbitMQ.RabbitMqDequeueStrategy.ConsumeMessages(Object state) in c:\BuildAgent\work\ef98ad7376e3379a\src\NServiceBus.RabbitMQ\RabbitMqDequeueStrategy.cs:line 234
   at System.Threading.Tasks.Task.Execute()
```

Where **SOME_QUEUE** is one of ```OurCustomHostEndpoint```, ```OurCustomHostEndpoint.TimeoutsDispatcher```, ```OurCustomHostEndpoint.Timeouts``` sort of queues.

Also (more rare):

```
2016-02-01 00:05:01.8661 INFO Disconnected from RabbitMQ Broker, reason: AMQP close-reason, initiated by Library, code=541, text="Unexpected Exception", classId=0, methodId=0, cause=System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.Impl.Frame.ReadFrom(NetworkBinaryReader reader)
   at RabbitMQ.Client.Impl.SocketFrameHandler.ReadFrame()
   at RabbitMQ.Client.Framing.Impl.Connection.MainLoopIteration()
   at RabbitMQ.Client.Framing.Impl.Connection.MainLoop() , going to reconnect 
```

These errors are usually interleaved with stuff like:

```
2016-01-21 10:47:54.9765 INFO The circuit breaker for RabbitMqConnectivity is now in the armed state 
```
and
```
2016-01-21 10:47:53.9923 INFO The circuit breaker for RabbitMqConnectivity is now disarmed 
```
and sometimes in a rapid succession:

```
2016-02-01 05:47:43.4825 INFO The circuit breaker for RabbitMqConnectivity is now disarmed 
2016-02-01 05:47:43.4825 INFO The circuit breaker for RabbitMqConnectivity is now disarmed 
2016-02-01 05:47:43.4825 INFO The circuit breaker for RabbitMqConnectivity is now disarmed 
```

A continuous log file sample:

```
2016-02-01 06:02:58.4569 ERROR Failed to receive messages from **SOME_QUEUE**.Retries 
One or more errors occurred. System.AggregateException: One or more errors occurred. ---> System.IO.EndOfStreamException: SharedQueue closed
   at RabbitMQ.Util.SharedQueue`1.EnsureIsOpen()
   at RabbitMQ.Util.SharedQueue`1.Dequeue(Int32 millisecondsTimeout, T& result)
   at NServiceBus.Transports.RabbitMQ.RabbitMqDequeueStrategy.ConsumeMessages(Object state) in c:\BuildAgent\work\ef98ad7376e3379a\src\NServiceBus.RabbitMQ\RabbitMqDequeueStrategy.cs:line 234
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.EndOfStreamException: SharedQueue closed
   at RabbitMQ.Util.SharedQueue`1.EnsureIsOpen()
   at RabbitMQ.Util.SharedQueue`1.Dequeue(Int32 millisecondsTimeout, T& result)
   at NServiceBus.Transports.RabbitMQ.RabbitMqDequeueStrategy.ConsumeMessages(Object state) in c:\BuildAgent\work\ef98ad7376e3379a\src\NServiceBus.RabbitMQ\RabbitMqDequeueStrategy.cs:line 234
   at System.Threading.Tasks.Task.Execute()<---
  
SharedQueue closed System.IO.EndOfStreamException: SharedQueue closed
   at RabbitMQ.Util.SharedQueue`1.EnsureIsOpen()
   at RabbitMQ.Util.SharedQueue`1.Dequeue(Int32 millisecondsTimeout, T& result)
   at NServiceBus.Transports.RabbitMQ.RabbitMqDequeueStrategy.ConsumeMessages(Object state) in c:\BuildAgent\work\ef98ad7376e3379a\src\NServiceBus.RabbitMQ\RabbitMqDequeueStrategy.cs:line 234
   at System.Threading.Tasks.Task.Execute() Void EnsureIsOpen()    at RabbitMQ.Util.SharedQueue`1.EnsureIsOpen()
   at RabbitMQ.Util.SharedQueue`1.Dequeue(Int32 millisecondsTimeout, T& result)
   at NServiceBus.Transports.RabbitMQ.RabbitMqDequeueStrategy.ConsumeMessages(Object state) in c:\BuildAgent\work\ef98ad7376e3379a\src\NServiceBus.RabbitMQ\RabbitMqDequeueStrategy.cs:line 234
   at System.Threading.Tasks.Task.Execute()
2016-02-01 06:03:01.5095 INFO The circuit breaker for RabbitMqConnectivity is now disarmed 
2016-02-01 06:03:01.5095 INFO The circuit breaker for RabbitMqConnectivity is now disarmed 
2016-02-01 06:03:01.5095 INFO The circuit breaker for RabbitMqConnectivity is now disarmed 
2016-02-01 06:03:01.5095 INFO The circuit breaker for RabbitMqConnectivity is now disarmed 
2016-02-01 06:03:41.2768 DEBUG Polling for timeouts at 01/02/2016 06:03:41. 
2016-02-01 06:03:41.2988 DEBUG Polling next retrieval is at 01/02/2016 06:04:41. 
2016-02-01 06:04:41.3328 DEBUG Polling for timeouts at 01/02/2016 06:04:41. 
2016-02-01 06:04:41.3941 DEBUG Polling next retrieval is at 01/02/2016 06:05:41. 
2016-02-01 06:05:41.4247 DEBUG Polling for timeouts at 01/02/2016 06:05:41. 
2016-02-01 06:05:41.4537 DEBUG Polling next retrieval is at 01/02/2016 06:06:41.
```

This is a big problem for us, because it would be not great to have this in production suddenly one day. Even if our network connections are not reliable for whatever reason the message queues should really get processed eventually. Besides this error is quite chatty so I cannot divert it to email log to avoid getting spammed.

It's also hard to reproduce because it's intermittent and the cause is not known.

Config details:

```
            new SecondLevelRetriesConfig
            {
                Enabled = true,
                TimeIncrease = TimeSpan.FromSeconds(10),
                NumberOfRetries = 3
            };
//...
            new TransportConfig
            {
                MaxRetries = 5,
                MaximumConcurrencyLevel = 8,
                MaximumMessageThroughputPerSecond = 100
            };
//...
            busConfiguration.UseContainer<AutofacBuilder>(c => c.ExistingLifetimeScope(BuildContainer()));
            busConfiguration.UseTransport<RabbitMQTransport>();
            busConfiguration.UseSerialization<JsonSerializer>();
            busConfiguration.UsePersistence<NHibernatePersistence>();
            busConfiguration.EnableInstallers();
            busConfiguration.EnableOutbox();
            busConfiguration.Transactions().IsolationLevel(IsolationLevel.ReadCommitted);
            busConfiguration.EndpointName(GetEndpointName());
            busConfiguration.PurgeOnStartup(false);
            busConfiguration.Conventions().DefiningEventsAs(t => typeof (IEvent).IsAssignableFrom(t) || t.Namespace != null && t.Namespace.StartsWith("ServiceControl.Contracts"));
```

My guesses:

 - Could it be some sort of Rabbit MQ integration stability problem where it would eventually stop working after many instances of dropped connections?

 - Could it be some sort of circuit breaker bug where it would eventually "give up" on retrying?

Please let me know if I can give any extra details. Thank you.

**Comment by dsaf** [comment]
Could be related to #63?

**Comment by andreasohlund** [comment]
Are you using the nservicebus host or are you self hosting?

**Comment by andreasohlund** [comment]
`The circuit breaker for RabbitMqConnectivity is now disarmed ` should mean that connectivity to the broker is restored but the behavior you see is that no message are processed?

Are there any channels open from the endpoint if you look in the rabbitmq management UI?

**Comment by bording** [comment]
@dsaf In your log example, there are lines showing that the circuit breaker has been disarmed:
`The circuit breaker for RabbitMqConnectivity is now disarmed`

but I don't see any lines that indicate that it has been armed in the first place:
`The circuit breaker for RabbitMqConnectivity is now in the armed state`

I would be expecting to see these after the `Failed to receive messages` lines and before for the disarming lines.

Are you seeing any of these lines in your log files?

**Comment by dsaf** [comment]
@andreasohlund

> Are you using the nservicebus host or are you self hosting?

I am using NServiceBus Host.

> ```The circuit breaker for RabbitMqConnectivity is now disarmed``` should mean that connectivity to the broker is restored but the behavior you see is that no message are processed?

Yes, there was no processing going on, until I restarted the host windows service.

> Are there any channels open from the endpoint if you look in the rabbitmq management UI?

I am pretty sure I have seen a few channels, but cannot prove it now (since I restarted the host and it cleared the queue etc.). Also we have more than one host on the same box - I forgot to mention, sorry! There are five of them, each behaves differently. The one I am talking about is the most consistently intensive one in terms of processing and messaging.

@bording That log sample is a small but continuous piece of log without any gaps. But isn't the order of log entries non-deterministic due to concurrency meaning that the lines can be out of order? I will not have access to work machine until tomorrow GMT, so cannot read what is above that snippet to confirm :disappointed:.

**Comment by dsaf** [comment]
@andreasohlund 

This problem re-occured today again.

The problematic queue of the problematic host:

![image](https://cloud.githubusercontent.com/assets/3845650/12749482/d2e739c6-c9a8-11e5-808d-952d21074dcb.png)
![image](https://cloud.githubusercontent.com/assets/3845650/12749464/b60f6c9c-c9a8-11e5-8f45-5f641ca000f4.png)

Standard queues seem fine:

![image](https://cloud.githubusercontent.com/assets/3845650/12749480/d18e206c-c9a8-11e5-9f6a-9ffaf81a939e.png)
![image](https://cloud.githubusercontent.com/assets/3845650/12749475/c92d858e-c9a8-11e5-9d2b-7d327c20c4f9.png)

Messages are stuck:

![image](https://cloud.githubusercontent.com/assets/3845650/12749537/3c59a70e-c9a9-11e5-82ef-5b4903527c52.png)
![image](https://cloud.githubusercontent.com/assets/3845650/12749792/caba4dea-c9aa-11e5-85a4-2f8f35ce9005.png)

Connections (please keep in mind we have 5 (+1 disabled) hosts on the same box):

![image](https://cloud.githubusercontent.com/assets/3845650/12749153/ae9840c6-c9a6-11e5-951f-56a53bcf1589.png)
![image](https://cloud.githubusercontent.com/assets/3845650/12749140/9cba428c-c9a6-11e5-8667-9516ec3409e5.png)

Channels (is it normal to see so many even for 5 hosts?):

![image](https://cloud.githubusercontent.com/assets/3845650/12749284/7abe1ed2-c9a7-11e5-869b-86a3de644f2f.png)
![image](https://cloud.githubusercontent.com/assets/3845650/12749295/8a87e0c8-c9a7-11e5-98e8-367769719e78.png)
![image](https://cloud.githubusercontent.com/assets/3845650/12749315/b43112fa-c9a7-11e5-93cd-915c130525ec.png)
![image](https://cloud.githubusercontent.com/assets/3845650/12749326/cdcb3718-c9a7-11e5-9d0e-5f49968fe327.png)
![image](https://cloud.githubusercontent.com/assets/3845650/12749344/e5702306-c9a7-11e5-9f4d-4c873f252f41.png)
![image](https://cloud.githubusercontent.com/assets/3845650/12749349/f6afdeea-c9a7-11e5-8a1f-6a5307c9fcc9.png)

Nodes (we have few other smaller projects using same instance):

![image](https://cloud.githubusercontent.com/assets/3845650/12749425/6e623b72-c9a8-11e5-806e-10b1fbf908f0.png)

The log now just keeps spitting this for hours:

```
2016-02-02 12:45:09.9503 DEBUG Polling for timeouts at 02/02/2016 12:45:09. 
2016-02-02 12:45:10.4729 DEBUG Polling next retrieval is at 02/02/2016 12:46:10. 
```

**Comment by andreasohlund** [comment]
Seems like there is channels open to the broker but no messages are
received on them. As long as NSB thinks that the channel is ok it won't try
to recreate new ones. Can you upload the full logfile somewhere so that we
can take a look?

What is your handlers doing? (could it be that hey are hanging and there by
giving the impression that no messages are being processed)

Would you be able to take a process dump of the endpoint process and upload
as well? (right click =>create dump in TaskManager)

**Comment by dsaf** [comment]
> What is your handlers doing? (could it be that hey are hanging and there by
giving the impression that no messages are being processed)

There is definitely work for them to do, and I don't think they are stuck in our custom logic loop or something like that. It looks like they are not receiving any messages and thus just being idle. Is this what you've meant? We do have more than one saga and quite a few handlers.

> Can you upload the full logfile somewhere so that we can take a look?
> Would you be able to take a process dump of the endpoint process and upload
as well? 

Would it be OK to send them or hidden links to them to your a...d@particular.net email address? It would be nice not to share them publicly.

By the way I posted the issue here because it looks like a bug and also because GitHub is so convenient. Please let me know if you would prefer me to use an official support communication channel. Our licence has some non-critical incident support, but I am not sure when to use it. Thank you.

**Comment by dsaf** [comment]
@andreasohlund

**Comment by dsaf** [comment]
@andreasohlund 

I have also checked that the dump file is ~500MB uncompressed and ~150 compressed. Is it critical to have it?

**Comment by bording** [comment]
@dsaf I was going to open a support case on your behalf, but you don't have enough information on your GitHub profile for me to identify you in our support system.

If you could open a support case, then you can send us the log file, and I can give you a way that you can send us the dump file also.

**Comment by dsaf** [comment]
@bording Yes, it's a personal profile.

I have opened the Non Critical Case # 16781 with a log file attached. Please let me know how to upload the dump file.

**Comment by dsaf** [comment]
The problem was in our code.

The handler was hanging on all threads because our code was making a synchronous request without a connection timeout logic.
