### ISSUE TITLE
RabbitMQ transport not setting NServiceBus.LocalAddress

### ISSUE THREAD

**Issue by volak** [Particular/NServiceBus.RabbitMQ#129]
After switching to RabbitMQ instead of MSMQ I am getting a startup exception in NSB. 

 Trace:

```

2016-02-26 00:57:13,969 [1] INFO  NServiceBus.Licensing.LicenseManager [(null)] - Using license supplied via fluent API.
2016-02-26 00:57:14,107 [1] INFO  NServiceBus.Persistence.PersistenceStartup [(null)] - Activating persistence 'InMemoryPersistence' to provide storage for 'NServiceBus.Persistence.StorageType+Sagas' storage.
2016-02-26 00:57:14,108 [1] INFO  NServiceBus.Persistence.PersistenceStartup [(null)] - Activating persistence 'InMemoryPersistence' to provide storage for 'NServiceBus.Persistence.StorageType+Timeouts' storage.
2016-02-26 00:57:14,108 [1] INFO  NServiceBus.Persistence.PersistenceStartup [(null)] - Activating persistence 'InMemoryPersistence' to provide storage for 'NServiceBus.Persistence.StorageType+Subscriptions' storage.
2016-02-26 00:57:14,109 [1] INFO  NServiceBus.Persistence.PersistenceStartup [(null)] - Activating persistence 'InMemoryPersistence' to provide storage for 'NServiceBus.Persistence.StorageType+Outbox' storage.
2016-02-26 00:57:14,109 [1] INFO  NServiceBus.Persistence.PersistenceStartup [(null)] - Activating persistence 'InMemoryPersistence' to provide storage for 'NServiceBus.Persistence.StorageType+GatewayDeduplication' storage.
2016-02-26 00:57:15,062 [1] INFO  NServiceBus.Licensing.LicenseManager [(null)] - UpgradeProtectionExpiration: 08/03/2015 00:00:00
2016-02-26 00:57:15,072 [1] FATAL NServiceBus.GenericHost [(null)] - Exception when starting endpoint.
System.Collections.Generic.KeyNotFoundException: The given key (NServiceBus.LocalAddress) was not present in the dictionary.
   at NServiceBus.Settings.SettingsHolder.Get(String key) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 91
   at NServiceBus.Settings.SettingsHolder.Get[T](String key) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 23
   at NServiceBus.SettingsExtentions.LocalAddress(ReadOnlySettings settings) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\SettingsExtentions.cs:line 66
   at NServiceBus.Features.UnicastBus.Setup(FeatureConfigurationContext context) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Config\UnicastBus.cs:line 50
   at NServiceBus.Features.FeatureActivator.ActivateFeature(FeatureState featureState, IEnumerable`1 featuresToActivate, FeatureConfigurationContext context) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Features\FeatureActivator.cs:line 240
   at NServiceBus.Features.FeatureActivator.SetupFeatures(FeatureConfigurationContext context) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Features\FeatureActivator.cs:line 116
   at NServiceBus.Configure.Initialize() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Configure.cs:line 115
   at NServiceBus.Bus.Create(BusConfiguration configuration) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Bus.cs:line 17
   at NServiceBus.GenericHost.PerformConfiguration(Action`1 moreConfiguration) in c:\BuildAgent\work\a3de8759ee491634\src\NServiceBus.Hosting.Windows\GenericHost.cs:line 119
   at NServiceBus.GenericHost.Start() in c:\BuildAgent\work\a3de8759ee491634\src\NServiceBus.Hosting.Windows\GenericHost.cs:line 58
```

I did some digging, ConfigureTransport is being called but the FeatureActivator is not calling the set defaults function - presumably because some feature is not activated by me or RabbitMq.Transport.

If I manually enable MsmqTransportConfigurator the exception goes away... but thats not the right solution, indicating some kind of bug.

Here is how Im configuring NSB

```
config.EndpointName(endpoint);

            config.EnableInstallers();
            config.UseTransport<RabbitMQTransport>().CallbackReceiverMaxConcurrency(10);
            config.UsePersistence<InMemoryPersistence>();
            config.UseContainer<StructureMapBuilder>(c => c.ExistingContainer(_container));
            config.UseSerialization<NewtonsoftSerializer>();
            config.PurgeOnStartup(true);

            config.EnableFeature<Aggregates.Feature>();
            config.EnableFeature<Aggregates.GetEventStore.Feature>();
            config.DisableFeature<Sagas>();
            config.DisableFeature<SecondLevelRetries>();
            config.DisableFeature<AutoSubscribe>();
            
            config.Transactions().Disable().DisableDistributedTransactions();
```

This is inside a NSB.Host

**Comment by volak** [comment]
Figured out the issue - its still a bug but now we know why..

The assembly scanner is failing to scan the RabbitMQ Transport assembly due to a manifest error. (requesting version 3.5 of RabbitMQ.Client and finding version 3.5.7)
The fix was to update this library to compile with 3.5.7 - downgrading to 3.5 didn't fix it as I hoped

**Comment by andreasohlund** [comment]
What version of the "NServiceBus" package do you have?

**Comment by andreasohlund** [comment]
Also have you seen this: https://github.com/Particular/NServiceBus.RabbitMQ/issues/111#issuecomment-166362127

**Comment by volak** [comment]
everything is latest - minus RabbitMq.Client

5.2.14

I have the assembly redirect, but it still failed to load.  There is a breaking change in 3.5.7 vs 3.5.0 but I don't know if thats the reason.  It is also only an issue in my NSB.Host project.  I have 2 more, a regular console app and a web service which both started NSB with Rabbit just fine.  Took me hours to figure out the assembly wasn't getting scanned

**Comment by andreasohlund** [comment]
>I have the assembly redirect, but it still failed to load

Just double checking; You have the redirect in both nsb.host.exe.config and your "own" app.config?

**Comment by volak** [comment]
No... I've never had a Host.exe.config - yikes thats going to be a weird file to add to the project

**Comment by andreasohlund** [comment]
Yea, we're slowly moving away from the host in favor of https://github.com/Particular/NServiceBus.Bootstrap.WindowsService

I'm looking into the breaking changes in rabbit

http://apicomparer.particular.net/compare/rabbitmq.client/3.5.0...3.5.7

but they look ok from our perspective. Will digg deeper

**Comment by volak** [comment]
Yeah that SetPersistent method was what I had to change.  Wouldn't compile with the deprecated method but I guess that wouldn't matter if its redirected.

I added the new .config file and it works fine thanks

**Comment by andreasohlund** [comment]
Fyi, we'll release a 3.6 compatible version https://github.com/Particular/NServiceBus.RabbitMQ/issues/117

**Comment by volak** [comment]
I'm getting this same error trying to use NServiceBus.Hosting.Azure.HostProcess in a could service.. creating a NServiceBus.Hosting.Azure.HostProcess.config file doesn't seem to help - Im guessing because its run in one of the azure container programs.

I may keep poking at this, let you know if I figure out a way to fix the scanning issue
