### ISSUE TITLE
NServiceBus.RabbitMQ.Tests is not independently runnable

### ISSUE THREAD

**Issue by adamralph** [Particular/NServiceBus.RabbitMQ#264]
If I run `NServiceBus.RabbitMQ.Tests` against an empty virtual host, I get this failure: 

```
Test 'NServiceBus.Transport.RabbitMQ.Tests.When_consuming_messages.Should_move_message_without_message_id_to_error_queue' failed:
	RabbitMQ.Client.Exceptions.OperationInterruptedException : The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=404, text="NOT_FOUND - no queue 'error' in vhost '/'", classId=60, methodId=70, cause=
	at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout)
	at RabbitMQ.Client.Impl.ModelBase.BasicGet(String queue, Boolean noAck)
	at RabbitMQ.Client.Impl.AutorecoveringModel.BasicGet(String queue, Boolean noAck)
	When_consuming_messages.cs(60,0): at NServiceBus.Transport.RabbitMQ.Tests.When_consuming_messages.Should_move_message_without_message_id_to_error_queue()
```

It doesn't matter how any times I run it, I get the same failure.

If, however, I run `AcceptanceTests` *before* running `Tests`, then `Tests` succeeds. (Running `TransportTests` before `Tests` has no effect.)

**Comment by bording** [comment]
Ah, yeah, that makes sense, since that test just got added and is doing a BasicGet on the error queue. We'll need to add something to make sure the error queue exists first.
