### ISSUE TITLE
Exchange creation failing if local address overridden

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus.RabbitMQ#29]
### Who's affected

All users overriding the local address of the endpoint

### Symptoms

The endpoint fails when subscribing throwing the following exception: 

```
RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=404, text="NOT_FOUND - no exchange 'PubSub.Subscriber1.WhenPublishingAnEventWithOverriddenLocalAddress.RabbitMQ' in vhost '/'", classId=40, methodId=30, cause=
   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply()
   at RabbitMQ.Client.Impl.ModelBase.ModelRpc(MethodBase method, ContentHeaderBase header, Byte[] body)
   at RabbitMQ.Client.Framing.Impl.v0_9_1.Model._Private_ExchangeBind(String destination, String source, String routingKey, Boolean nowait, IDictionary`2 arguments)
   at RabbitMQ.Client.Impl.ModelBase.ExchangeBind(String destination, String source, String routingKey)
   at NServiceBus.Transports.RabbitMQ.Routing.ConventionalRoutingTopology.SetupSubscription(IModel channel, Type type, String subscriberName) in c:\Projects\NServiceBus.RabbitMQ\src\NServiceBus.RabbitMQ\Routing\ConventionalRoutingTopology.cs:line 34
   at NServiceBus.Transports.RabbitMQ.RabbitMqSubscriptionManager.Subscribe(Type eventType, Address publisherAddress) in c:\Projects\NServiceBus.RabbitMQ\src\NServiceBus.RabbitMQ\RabbitMqSubscriptionManager.cs:line 18
   at NServiceBus.Unicast.UnicastBus.Subscribe(Type messageType, Predicate`1 condition) in y:\BuildAgent\work\31f8c64a6e8a2d7c\src\NServiceBus.Core\Unicast\UnicastBus.cs:line 390
   at NServiceBus.Unicast.UnicastBus.Subscribe(Type messageType) in y:\BuildAgent\work\31f8c64a6e8a2d7c\src\NServiceBus.Core\Unicast\UnicastBus.cs:line 343
   at NServiceBus.Unicast.UnicastBus.Subscribe[T]() in y:\BuildAgent\work\31f8c64a6e8a2d7c\src\NServiceBus.Core\Unicast\UnicastBus.cs:line 334
```

**Comment by andreasohlund** [comment]
Fixed by https://github.com/Particular/NServiceBus.RabbitMQ/commit/df67c3c36c8053b53ad8bf61f865c38a61894e04
