### ISSUE TITLE
Flaky NServiceBus.AcceptanceTests.Scheduling.When_scheduling_a_recurring_task.Should_execute_the_task

### ISSUE THREAD

**Issue by adamralph** [Particular/NServiceBus.RabbitMQ#317]
This is the test which fails intermittently when I run the tests locally. It happens on maybe 1 in 3 runs. (It also happens when I have a fresh virtual host so I think I made a false correlation between success and having a fresh virtual host.) I've also observed the same failure on the CI server from time to time.

```
1) Error : NServiceBus.AcceptanceTests.Scheduling.When_scheduling_a_recurring_task.Should_execute_the_task
System.AggregateException : Test run failed due to one or more exceptions
  ----> System.Exception : Some failed messages were not handled by the recoverability feature.
   at NServiceBus.AcceptanceTesting.Support.ScenarioRunner.<Run>d__0.MoveNext() in C:\Build\src\NServiceBus.AcceptanceTesting\Support\ScenarioRunner.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.AcceptanceTesting.ScenarioWithContext`1.<Run>d__2.MoveNext() in C:\Build\src\NServiceBus.AcceptanceTesting\ScenarioWithContext.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at NUnit.Framework.Internal.ExceptionHelper.Rethrow(Exception exception)
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context)
--Exception
   at NServiceBus.AcceptanceTesting.Support.ScenarioRunner.<StopEndpoints>d__12.MoveNext() in C:\Build\src\NServiceBus.AcceptanceTesting\Support\ScenarioRunner.cs:line 335
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.AcceptanceTesting.Support.ScenarioRunner.<PerformScenarios>d__5.MoveNext() in C:\Build\src\NServiceBus.AcceptanceTesting\Support\ScenarioRunner.cs:line 212
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.AcceptanceTesting.Support.ScenarioRunner.<PerformTestRun>d__2.MoveNext() in C:\Build\src\NServiceBus.AcceptanceTesting\Support\ScenarioRunner.cs:line 141
```

**Comment by bording** [comment]
@adamralph What branches have you seen this failing on? I'm pretty sure there are fixes in the 6.1.0 acceptance test framework that should prevent this from being a problem.

**Comment by adamralph** [comment]
Given that we've updated to 6.1.1 now in the tests, I'll give this a few days and if I don't see the failure again, I'll withdraw this issue.

**Comment by WojcikMike** [comment]
I reviewed builder today and found this:
https://builds.particular.net/viewLog.html?buildTypeId=NServiceBusRabbitMQ_1Buil&buildId=203069&branch_NServiceBusRabbitMQ=311

On 2nd of Jan we had the same issue event that the branch has acceptance test framework in version 6.1.1. So the issue is still there.

**Comment by adamralph** [comment]
Closing. We can re-open if we see this test starting to fail intermittently again.
