### ISSUE TITLE
When binding name is too long the exception raised by the RabbitMQ client is meaningless

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.RabbitMQ#453]
A customer came to me with the following error at endpoint startup:

```
RabbitMQ.Client.Exceptions.WireFormattingException: Short string too long; UTF-8 encoded length=260, max=255
   at RabbitMQ.Client.Impl.WireFormatting.WriteShortstr(NetworkBinaryWriter writer, String val)
   at RabbitMQ.Client.Framing.Impl.QueueBind.WriteArgumentsTo(MethodArgumentWriter writer)
   at RabbitMQ.Client.Impl.Command.TransmitAsSingleFrame(Int32 channelNumber, Connection connection)
```

Customer was using `DirectRoutingTopology` and one binding was too long, the thing is that all their events inherit from a base class, thus binding name was `namespace-base-class.namespace-derived-class`. They added a new event where the entire string was 5 chars longer than allowed. Being the above error useless it took us, the customer and myself, nearly to hours to figure out what was going on and to identify the source of the error.

Given that we are creating those bindings we should wrap the broker exception in a custom one adding some details such as the entity name that is causing the failure.

**Comment by adamralph** [comment]
👍 thanks for raising @mauroservienti. I've renamed to reflect this as a new "feature".

**Comment by mauroservienti** [comment]
Thank you

**Comment by andreasohlund** [comment]
The description mentions DirectRoutingTopology which is pretty much no longer used but I assume the same thing could happen with the conventional one?

**Comment by bording** [comment]
> The description mentions DirectRoutingTopology which is pretty much no longer used

There's nothing that we've done that actually prevents people from using it, so I'm not sure that's actually true.

>  I assume the same thing could happen with the conventional one?

Yeah, there are some length limitations in there as well, so this could apply more generally. I've started looking at what could be done here.

**Comment by bording** [comment]
Looking at this a bit more, I do think there is more we can do here, but if we change the exception type we expose to users by wrapping the client exceptions in something like `Exception` instead, that is technically a breaking behavior change.

Would be be okay with going from throwing `RabbitMQ.Client.Exceptions.WireFormattingException` or `RabbitMQ.Client.Exceptions.OperationInterruptedException` to just `Exception` in a minor release?

**Comment by andreasohlund** [comment]
I personally think a minor is fine since there is no way for us to
guarantee that we don’t change code in a way that other exceptions couldn’t
be thrown.

But I think that you already answered your self
https://github.com/Particular/PlatformDevelopment/issues/2675#issuecomment-464787977
:)

**Comment by bording** [comment]
I do generally think that changing the exception type the way we'd need to here is a break. Someone could have code that is catching the existing exceptions and doing something in the catch blocks.

If we changed to `Exception`, then those catch blocks would no longer catch the exceptions, and we'd have broken them.

That's why I'm thinking we'd really need to wait for a new major to do this.

**Comment by andreasohlund** [comment]
I’m happy with that decision

**Comment by bording** [comment]
FYI to make this work the way we'd want to, we'd also need to stop swallowing exceptions in https://github.com/Particular/NServiceBus.RabbitMQ/blob/develop/src/NServiceBus.Transport.RabbitMQ/Routing/ConventionalRoutingTopology.cs#L138-L140
and https://github.com/Particular/NServiceBus.RabbitMQ/blob/develop/src/NServiceBus.Transport.RabbitMQ/Routing/DirectRoutingTopology.cs#L72-L76

which I think would probably be a good thing anyway, but this really gets outside the realm of what should be done in a minor.

I'll remove this from the 5.1.0 milestone, and we can revisit when we release a new major.

**Comment by tmasternak** [comment]
This will be solved when this [PR](https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/908) is merged to the Rabbit Client library.

**Comment by bording** [comment]
The client PR gets us most of the way there since it means the exception thrown from the client will contain the offending value, so it should be more obvious which string it is that is causing the problem.

We could leave this open to further improve things, trying to surface a "queue name too long" or "binding too long" exception that points user even more in the right direction, but I'm not sure if that's worth doing or not.
