### ISSUE TITLE
How can I create a queue (if doesn't exist) in my Startup class?

### ISSUE THREAD

**Issue by samueleresca** [Particular/NServiceBus.RabbitMQ#510]
Hi, 
Is it possible to change the default behavior of the `EndpointConfiguration` class and create a queue if doesn't exist?

For example, the following `Startup` extension method: [EventsExtensions.cs](https://github.com/samueleresca/VinylStore.Catalog.API/blob/Service-ecosystem-patterns/src/VinylStore.Catalog.Infrastructure/Extensions/EventsExtensions.cs)
 
Throws the following exception during the startup time if the queue doesn't exist:

```
2018-12-26 13:30:18.138 FATAL NServiceBus.ReceiveComponent Receiver Main failed to start.
RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=404, text="NOT_FOUND - no queue 'ItemSoldOut' in vhost '/'", classId=60, methodId=20, cause=
   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout)
   at RabbitMQ.Client.Impl.ModelBase.BasicConsume(String queue, Boolean autoAck, String consumerTag, Boolean noLocal, Boolean exclusive, IDictionary`2 arguments, IBasicConsumer consumer)
   at RabbitMQ.Client.Impl.AutorecoveringModel.BasicConsume(String queue, Boolean autoAck, String consumerTag, Boolean noLocal, Boolean exclusive, IDictionary`2 arguments, IBasicConsumer consumer)
   at RabbitMQ.Client.IModelExensions.BasicConsume(IModel model, String queue, Boolean autoAck, String consumerTag, IBasicConsumer consumer)
   at NServiceBus.Transport.RabbitMQ.MessagePump.Start(PushRuntimeSettings limitations) in C:\BuildAgent\work\15dcdbe5f88af6ed\src\NServiceBus.Transport.RabbitMQ\Receiving\MessagePump.cs:line 111
   at NServiceBus.TransportReceiver.Start() in C:\BuildAgent\work\ed946b9f0e4aae01\src\NServiceBus.Core\Transports\TransportReceiver.cs:line 47
   at NServiceBus.ReceiveComponent.Start() in C:\BuildAgent\work\ed946b9f0e4aae01\src\NServiceBus.Core\Receiving\ReceiveComponent.cs:line 91

```

**Comment by bording** [comment]
@samueleresca Yes that is possible. You need to enable installers: https://docs.particular.net/nservicebus/operations/installers#running-installers

**Comment by samueleresca** [comment]
Hi @bording,
Thank you for the answer. Are installers enabled to use built-in dependency injection of ASP.NET Core?

**Comment by bording** [comment]
> Are installers enabled to use built-in dependency injection of ASP.NET Core?

@samueleresca I'm not sure I understand the question. What role are you thinking our installers would play here?

**Comment by samueleresca** [comment]
I need something (a callback/a hook/something else)  that allows me to create a queue if it doesn't exist.  it should be executed just before the `EndpointConfiguration.Start()` method.

The installer seems to be the right tool for the job: `Installers ensure that endpoint-specific artifacts (e.g. database tables, queues, directories, etc.) are created and configured when the endpoint is started.`

Furthermore, I need to pass the queue name to the installer class by using the built-in dependency injection provided by ASP.NET Core. 

Something like:

```

public class MyInstaller :
    INeedToInstallSomething
{
    private readonly IMySettings _mySettings;

    public MyInstaller(IMySettings mySettings){
         _mySettings = mySettings;
    }
    public Task Install(string identity)
    {
        //Do stuff with _mySettings.QueueName
        return Task.CompletedTask;
    }
}

```

Is that possible?

**Comment by bording** [comment]
You don't need to write an installer to have the endpoint's queues created. We will do that for you if installers are enabled.

**Comment by samueleresca** [comment]
Hi @bording , Thank you for the support. I have totally misunderstood the point of installers. Just checked and it works.

Closing now.
