### ISSUE TITLE
InvalidOperationException thrown from ContextBag.Merge

### ISSUE THREAD

**Issue by bording** [Particular/NServiceBus.RabbitMQ#515]
When processing messages from the main queue and satellite queues simultaneously, an `InvalidOperationException` can be thrown in the main pipeline.

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at NServiceBus.Extensibility.ContextBag.Merge(ContextBag context)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.RabbitMQ.MessagePump.<Process>d__29.MoveNext()
   ```

This can occur when a satellite message is processed at the same time as a main queue message because the transport is sharing a `ContextBag` instance.

## Who's affected
- Any user with an endpoint that is processing messages on the main queue and a satellite can potentially be affected.

## Symptoms
- Log entries are seen saying a message is being retried because of the following exception: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

### Backported to
- 4.4.3 #514

Originally reported in https://github.com/Particular/ServiceControl/issues/1550

**Comment by bording** [comment]
Fixed by #513
