### ISSUE TITLE
Intermittent acceptance tests failures

### ISSUE THREAD

**Issue by adamralph** [Particular/NServiceBus.RabbitMQ#95]
`NServiceBus.AcceptanceTests.Retries. When_sending_to_slr.Should_preserve_the_original_body_for_serialization_exceptions`

```
Test(s) failed. System.AggregateException : Test run failed due to one or more exception
  ----> System.Exception : Stopping endpoints took longer than 2 minutes
   at NServiceBus.AcceptanceTesting.Support.ScenarioRunner.Run(IList`1 runDescriptors, IList`1 behaviorDescriptors, IList`1 shoulds, Func`2 done, Int32 limitTestParallelismTo, Action`1 reports, Func`2 allowedExceptions) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.AcceptanceTesting\Support\ScenarioRunner.cs:line 85
   at NServiceBus.AcceptanceTesting.ScenarioWithContext`1.Run(RunSettings settings) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.AcceptanceTesting\ScenarioWithContext.cs:line 75
   at NServiceBus.AcceptanceTesting.ScenarioWithContext`1.NServiceBus.AcceptanceTesting.Support.IScenarioWithEndpointBehavior<TContext>.Run(Nullable`1 testExecutionTimeout) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.AcceptanceTesting\ScenarioWithContext.cs:line 112
   at NServiceBus.AcceptanceTests.Retries.When_sending_to_slr.Should_preserve_the_original_body_for_serialization_exceptions() in c:\BuildAgent\work\ef98ad7376e3379a\src\NServiceBus.RabbitMQ.AcceptanceTests\App_Packages\NSB.AcceptanceTests.5.2.0\Retries\When_sending_to_slr.cs:line 60
--Exception
   at NServiceBus.AcceptanceTesting.Support.ScenarioRunner.StopEndpoints(IEnumerable`1 endpoints) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.AcceptanceTesting\Support\ScenarioRunner.cs:line 313
   at NServiceBus.AcceptanceTesting.Support.ScenarioRunner.PerformScenarios(RunDescriptor runDescriptor, IEnumerable`1 runners, Func`1 done) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.AcceptanceTesting\Support\ScenarioRunner.cs:line 267
   at NServiceBus.AcceptanceTesting.Support.ScenarioRunner.PerformTestRun(IList`1 behaviorDescriptors, IList`1 shoulds, RunDescriptor runDescriptor, Func`2 done, Func`2 allowedExceptions) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.AcceptanceTesting\Support\ScenarioRunner.cs:line 165
------- Stderr: -------
Parallelism limited to: 1
RabbitMQTransport - Started @ 6/5/2015 8:46:34 AM
Stopping endpoint: SendingToSlr.RetryEndpoint
Unhandled exception in remote appdomain: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Threading.Thread.InternalCrossContextCallback(Context ctx, IntPtr ctxID, Int32 appDomainID, InternalCrossContextDelegate ftnToCall, Object[] args)
   at System.Runtime.Remoting.Channels.CrossContextChannel.SyncProcessMessage(IMessage reqMsg)
   at System.Runtime.Remoting.Proxies.RemotingProxy.CallProcessMessage(IMessageSink ms, IMessage reqMsg, ArrayWithSize proxySinks, Thread currentThread, Context currentContext, Boolean bSkippingContextChain)
   at System.Runtime.Remoting.Proxies.RemotingProxy.InternalInvoke(IMethodCallMessage reqMcmMsg, Boolean useDispatchMessage, Int32 callType)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NServiceBus.AcceptanceTests.Retries.When_sending_to_slr.Context.set_FinishedMessageProcessingCalledAfterFaultManagerInvoked(Boolean value)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at NServiceBus.Unicast.Transport.TransportReceiver.ProcessMessage(TransportMessage message) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 351
   at NServiceBus.Unicast.Transport.TransportReceiver.TryProcess(TransportMessage message) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 230
   at NServiceBus.Transports.RabbitMQ.RabbitMqDequeueStrategy.ConsumeMessages(Object state) in c:\BuildAgent\work\ef98ad7376e3379a\src\NServiceBus.RabbitMQ\RabbitMqDequeueStrategy.cs:line 193
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
RabbitMQTransport - Finished @ 6/5/2015 8:48:35 AM
Test run aborted due to test failures
------------------------------------------------------
Test summary for: RabbitMQTransport
Using settings:
   Transport: NServiceBus.RabbitMQTransport, NServiceBus.Transports.RabbitMQ, Version=2.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c
   Transport.ConnectionString: host=localhost
Endpoints:
     - SendingToSlr.RetryEndpoint
Test failed: System.Exception: Stopping endpoints took longer than 2 minutes
   at NServiceBus.AcceptanceTesting.Support.ScenarioRunner.StopEndpoints(IEnumerable`1 endpoints) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.AcceptanceTesting\Support\ScenarioRunner.cs:line 313
   at NServiceBus.AcceptanceTesting.Support.ScenarioRunner.PerformScenarios(RunDescriptor runDescriptor, IEnumerable`1 runners, Func`1 done) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.AcceptanceTesting\Support\ScenarioRunner.cs:line 267
   at NServiceBus.AcceptanceTesting.Support.ScenarioRunner.PerformTestRun(IList`1 behaviorDescriptors, IList`1 shoulds, RunDescriptor runDescriptor, Func`2 done, Func`2 allowedExceptions) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.AcceptanceTesting\Support\ScenarioRunner.cs:line 165
Context:
FinishedMessageProcessingCalledAfterFaultManagerInvoked = False
FaultManagerInvoked = True
OriginalBodyChecksum = 85
SlrChecksum = 85
SimulateSerializationException = True
EndpointsStarted = True
Exceptions = 
HasNativePubSubSupport = True
Trace:
------------------------------------------------------
```

**Comment by adamralph** [comment]
I'm not sure what label to give this. Do we need a new one? 'Build'?

**Comment by andreasohlund** [comment]
I´d say `Internal refactoring` for now?

**Comment by bording** [comment]
I've not seen anything like this while working on the v6 4.0 release.

I'm not really seeing anything actionable here. Do we need to keep this open?
